spring:
  main:
    log-startup-info: false
    banner-mode: off

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: schema.sql
    data: data.sql
    sqlScriptEncoding: UTF-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
#    show-sql: true

logging:
  level:
    ROOT: ERROR
