spring:
  main:
    log-startup-info: false
    banner-mode: off

  data:
    mongodb:
#      uri: mongodb://localhost
#      port: 27017
      database: home_library
#      database: test

logging:
  level:
    ROOT: ERROR
